# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Evpat\PycharmProjects\ArtekPyQt5\PyQt5\rasp.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtCore import QTimer
from PyQt5.QtGui import QCursor

import sys
from PyQt5.QtGui     import *
from PyQt5.QtCore    import *
from PyQt5.QtWidgets import *

class Tab(QDialog):
    def __init__(self, parent=None):
        super(Tab, self).__init__(parent)
        self.setObjectName("tab_3")

        #self.installEventFilter(self)

    def eventFilter(self, obj, event):
        if event.type() == QEvent.MouseButtonPress:
            import qt_run
            mouseEvent = QMouseEvent(event)
            tip = 0
            if mouseEvent.buttons() == Qt.LeftButton:
                tip = 0
                ui.textEdit.setText("Нажали левую кнопку мыши")
            elif mouseEvent.buttons() == Qt.MidButton:
                tip = 1
                ui.textEdit.setText("Нажали среднюю кнопку мыши")
            elif mouseEvent.buttons() == Qt.RightButton:
                tip = 2
                ui.textEdit.setText("Нажали правую кнопку мыши")
            qt_run.click(obj, tip)
        # здесь отфильтруйте событие выпуска мыши и перепишите его поведение
        #if event.type() == QEvent.MouseButtonRelease:
        #    self.labelState.setText("Отпустили кнопку мыши")
        #    self.label1.setPixmap(QPixmap.fromImage(self.image1))
        return QDialog.eventFilter(self, obj, event)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Расписание")
        MainWindow.resize(1800, 980)

        self.timer = QTimer()

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(50, 80, 451, 171))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.load_grp_2 = QtWidgets.QGroupBox(self.tab_2)
        self.load_grp_2.setFlat(False)
        self.load_grp_2.setCheckable(False)
        self.load_grp_2.setObjectName("groupBox_1")
        self.load_le = []
        self.load_lbl = []
        self.load_layout_2 = QtWidgets.QGridLayout(self.load_grp_2)
        for i in range(7):
            self.load_le.append(QtWidgets.QLineEdit(self.load_grp_2))
            self.load_lbl.append(QtWidgets.QLabel(self.load_grp_2))
            self.load_lbl[i].setText("<html><head/><body><p><span style=\" font-weight:600;\">"+str(i + 5)+"</span></p></body></html>")
            self.load_layout_2.addWidget(self.load_lbl[i], i, 0, 1, 1)
            self.load_layout_2.addWidget(self.load_le[i], i, 1, 1, 1)

        self.gridLayout_3.addWidget(self.load_grp_2, 0, 1, 1, 1)
        self.load_grp_1 = QtWidgets.QGroupBox(self.tab_2)
        self.load_grp_1.setObjectName("load_grp_1")
        self.lineEdit_days = QtWidgets.QLineEdit(self.load_grp_1)
        self.lineEdit_days.setGeometry(QtCore.QRect(40, 20, 41, 22))
        self.lineEdit_days.setObjectName("lineEdit_days")
        self.gridLayout_3.addWidget(self.load_grp_1, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setAutoScrollMargin(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1586, 503))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.gridTechLoad = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridTechLoad.setObjectName("gridTechLoad")

        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 4)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 5)
        self.gridLayout_3.setColumnStretch(3, 12)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = Tab()
        #self.tab_3 = QtWidgets.QWidget()
        #self.tab_3.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1640, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action3 = QtWidgets.QAction(MainWindow)
        self.menu.addAction(self.action1)
        self.menu.addAction(self.action2)
        self.menu.addAction(self.action3)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.label4 = QtWidgets.QLabel(self.tab)
        self.label4.setGeometry(QtCore.QRect(100, 100, 1000, 100))
        self.a = 0
        self.label4.setText("LOHAAAA")

        self.label4.installEventFilter(MainWindow)

        # Это для связи между модулями

        # Конец связи для модулей

        #self.but2 = QtWidgets.QPushButton('Нажми меня')
        #self.but2.setGeometry(0, 0, 100, 100)
        #self.load_layout_2.addWidget(self.but2, 0, 0, 1, 1)
        #self.but2.clicked.connect(self.error)

        self.grp_clas = []
        self.grp_clas_ = []
        self.grp_clas_u = []
        self.layout_clas = []
        self.layout_clas_ = []
        self.layout_clas_u = []
        self.lbl_clas = []
        self.lbl_clas_ = []
        self.lbl_clas_u = []
        self.indicator_lbl_clas = []
        self.indicator_lbl_clas_u = []

        self.grp_teach = []
        self.grp_teach_ = []
        self.grp_teach_u = []
        self.layout_teach = []
        self.layout_teach_ = []
        self.layout_teach_u = []
        self.lbl_teach = []
        self.lbl_teach_ = []
        self.lbl_teach_u = []
        self.indicator_lbl_teach = []
        self.indicator_lbl_teach_u = []


    def error(self):
        raise Exception('Неожиданная ошибкочка')

    def eventFilter(self, obj, event):
        print("ASDASD")
        # Только фильтровать событие label1, переписать его поведение,
        # другие события будут проигнорированы
        if obj == self.label4:
            # здесь отфильтруйте событие mouse и перепишите его поведение
            if event.type() == QEvent.MouseButtonPress:
                mouseEvent = QMouseEvent(event)
                if mouseEvent.buttons() == Qt.LeftButton:
                    print("Нажали левую кнопку мыши")
                elif mouseEvent.buttons() == Qt.MidButton:
                    print("Нажали среднюю кнопку мыши")
                elif mouseEvent.buttons() == Qt.RightButton:
                    print("Нажали правую кнопку мыши")

            # здесь отфильтруйте событие выпуска мыши и перепишите его поведение

        return True

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Учителя"))
        self.load_grp_2.setTitle(_translate("MainWindow", "Количество классов"))
        """
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">7</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">11</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">6</span></p><p><br/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">9</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">8</span></p><p><br/></p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">5</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">10</span></p></body></html>"))
        """
        self.load_grp_1.setTitle(_translate("MainWindow", "Количество дней"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Р"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "И"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "М"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ф"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Х"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "О"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "11"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "Нагрузка учителей"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Нагрузка"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Генерация"))

        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.action1.setText(_translate("MainWindow", "Сохранить файл"))
        self.action2.setText(_translate("MainWindow", "Открыть файл"))
        self.action3.setText(_translate("MainWindow", "Открыть файлы"))

#    def open(self, filename):

#    def save(self, filename):
#        return open(filename, 'w')


import sys


def my_excepthook(type, value, tback):
    QtWidgets.QMessageBox.critical(
        MainWindow, "CRITICAL ERROR", str(value),
        QtWidgets.QMessageBox.Cancel
    )
    sys.__excepthook__(type, value, tback)


sys.excepthook = my_excepthook


app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
#MainWindow.setStyleSheet("QLabel{font-size: 12pt;}")
MainWindow.show()
